#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "wikijs"
name = "Wiki.js"
description.en = "Powerful and extensible Wiki"
description.fr = "Wiki puissant et extensible"

version = "2.5.307~ynh1"

maintainers = ["yalh76"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://wiki.js.org/"
demo = "https://docs-beta.requarks.io/"
userdoc = "https://docs-beta.requarks.io/"
code = "https://github.com/Requarks/wiki"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = true

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    in_subdir = false
    url = "https://github.com/requarks/wiki/releases/download/v2.5.307/wiki-js.tar.gz"
    sha256 = "c0495704454baab2be5adb02530d4879f581a86e9de8b3f4795ca53dbe2a5d8d"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "wiki-js.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false

    [resources.ports]

    [resources.apt]
    packages = "postgresql"

    [resources.database]
    type = "postgresql"
