packaging_format = 2

id = "wikijs"
name = "Wiki.js"
description.en = "Open source powerful wiki app built on Node.js, Git and Markdown"
description.fr = "Wiki open source propulsé par Node.js, Git et Markdown"

version = "2.5.298~ynh1"

maintainers = ["yalh76"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://wiki.js.org/"
demo = "https://docs-beta.requarks.io/"
userdoc = "https://docs-beta.requarks.io/"
code = "https://github.com/Requarks/wiki"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = true
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/Requarks/wiki/releases/download/v2.5.298/wiki-js.tar.gz"
        sha256 = "3bb290d77e3387dba5958c906629a6c5f751c17787903f1a021cbfa51cc88f1a"
        in_subdir = false

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false

    [resources.apt]
    packages = "postgresql"

    [resources.database]
    type = "postgresql"
