#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status $app >/dev/null; then
    yunohost service remove "$app"
fi

# Remove the dedicated systemd config
ynh_config_remove_systemd

# Remove the dedicated NGINX config
ynh_config_remove_nginx

# Remove metapackage and its dependencies
ynh_nodejs_remove

yunohost user delete $ldap_user --purge

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
